{"name": "test_zone_list_loaded", "status": "skipped", "statusDetails": {"message": "Skipped: Appium 연결 실패: Message: Could not find a connected Android device in 20000ms\nStacktrace:\nUnknownError: Could not find a connected Android device in 20000ms\n    at getResponseForW3CError (C:\\Users\\tslee\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\errors.ts:1103:34)\n    at asyncHandler (C:\\Users\\tslee\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\protocol\\protocol.ts:507:57)\nThe above error is caused by\nError: Could not find a connected Android device in 20000ms\n    at ADB.getDevicesWithRetry (C:\\Users\\tslee\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-adb\\lib\\tools\\system-calls.js:295:13)\n    at AndroidUiautomator2Driver.getDeviceInfoFromCaps (C:\\Users\\tslee\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-android-driver\\lib\\commands\\device\\common.js:41:21)\n    at AndroidUiautomator2Driver.createSession (C:\\Users\\tslee\\.appium\\node_modules\\appium-uiautomator2-driver\\lib\\driver.ts:361:30)\n    at AppiumDriver.createSession (C:\\Users\\tslee\\AppData\\Roaming\\npm\\node_modules\\appium\\lib\\appium.js:360:35)", "trace": "('C:\\\\Users\\\\tslee\\\\Desktop\\\\김선아\\\\ddokta-e2e-automation\\\\mobile\\\\tests\\\\test_zone_list.py', 18, 'Skipped: Appium 연결 실패: Message: Could not find a connected Android device in 20000ms\\nStacktrace:\\nUnknownError: Could not find a connected Android device in 20000ms\\n    at getResponseForW3CError (C:\\\\Users\\\\tslee\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\protocol\\\\errors.ts:1103:34)\\n    at asyncHandler (C:\\\\Users\\\\tslee\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\protocol\\\\protocol.ts:507:57)\\nThe above error is caused by\\nError: Could not find a connected Android device in 20000ms\\n    at ADB.getDevicesWithRetry (C:\\\\Users\\\\tslee\\\\.appium\\\\node_modules\\\\appium-uiautomator2-driver\\\\node_modules\\\\appium-adb\\\\lib\\\\tools\\\\system-calls.js:295:13)\\n    at AndroidUiautomator2Driver.getDeviceInfoFromCaps (C:\\\\Users\\\\tslee\\\\.appium\\\\node_modules\\\\appium-uiautomator2-driver\\\\node_modules\\\\appium-android-driver\\\\lib\\\\commands\\\\device\\\\common.js:41:21)\\n    at AndroidUiautomator2Driver.createSession (C:\\\\Users\\\\tslee\\\\.appium\\\\node_modules\\\\appium-uiautomator2-driver\\\\lib\\\\driver.ts:361:30)\\n    at AppiumDriver.createSession (C:\\\\Users\\\\tslee\\\\AppData\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\lib\\\\appium.js:360:35)')"}, "description": "Zone 목록이 정상적으로 로드되는지 확인", "attachments": [{"name": "log", "source": "561457f9-111f-4f11-b9a0-236ea64d05f5-attachment.txt", "type": "text/plain"}], "start": 1760879518653, "stop": 1760879518653, "uuid": "e857275a-27cc-4583-8b31-618398ae1288", "historyId": "eb433c9cc6a02f57f8fa51b56074738a", "testCaseId": "eb433c9cc6a02f57f8fa51b56074738a", "fullName": "mobile.tests.test_zone_list.TestZoneListUI#test_zone_list_loaded", "labels": [{"name": "parentSuite", "value": "mobile.tests"}, {"name": "suite", "value": "test_zone_list"}, {"name": "subSuite", "value": "TestZoneListUI"}, {"name": "host", "value": "DESKTOP-27T24JT"}, {"name": "thread", "value": "30896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "mobile.tests.test_zone_list"}]}